[build]
  base = "/"

  publish = "/"

  functions = "functions/"
[dev]
  base = "/"

  publish = "/"

  functions = "functions/"
[production]
  base = "/"

  publish = "/"

  functions = "functions/"